[2023-06-09 21:52:36,114][app.py:1742][ERROR][140072028464896] - Exception on /api/ApeConfig/webtest [PUT]
Traceback (most recent call last):
  File "/home/ape/miniconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ape/miniconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ape/miniconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 1842, in finalize_request
    response = self.make_response(rv)
  File "/home/ape/miniconda3/envs/flask/lib/python3.7/site-packages/flask/app.py", line 2135, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'ApeConfig.web_Test' did not return a valid response. The function either returned None or ended without a return statement.
